# CrowdSec Profiles Configuration
# Defines actions to take when scenarios trigger

name: default_ip_remediation
filters:
  - Alert.Remediation == true && Alert.GetScope() == "Ip"
decisions:
  - type: ban
    duration: 4h
on_success: break
---
name: rate_limit_remediation  
filters:
  - Alert.Remediation == true && Alert.GetScenario() contains "http-sensitive"
decisions:
  - type: throttle
    duration: 30m
on_success: break
---
name: bot_captcha
filters:
  - Alert.Remediation == true && Alert.GetScenario() contains "bot"
decisions:
  - type: captcha
    duration: 1h
on_success: break
